"""Discord APK patcher engine."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from ..context import Context
from ..utils import check_dependencies, clone_repository

# Constants
DISCORD_PATCHER_REPO = "https://github.com/CyberL1/discord-apk-patcher"
REQUIRED_TOOLS = ["apktool", "zipalign", "apksigner", "keytool"]


def _create_settings_env(
  patcher_dir: Path, input_apk: Path, ctx: Context
) -> Path:
  """
  Create settings.env configuration file.

  Args:
      patcher_dir: Discord patcher directory.
      input_apk: Input APK path.
      ctx: Pipeline context.

  Returns:
      Path to settings.env file.
  """
  settings_file = patcher_dir / "settings.env"

  # Get custom settings from context or use defaults
  keystore_path = ctx.options.get(
    "discord_keystore", str(patcher_dir / "keystore.jks")
  )
  keystore_pass = ctx.options.get("discord_keystore_pass", "android")
  discord_version = ctx.options.get("discord_version", "auto")

  settings_content = f"""# Discord APK Patcher Settings
# Generated by apk-tweak pipeline

# Input APK
INPUT_APK={input_apk}

# Output directory
OUTPUT_DIR={ctx.output_dir}

# Keystore configuration
KEYSTORE_PATH={keystore_path}
KEYSTORE_PASS={keystore_pass}
KEY_ALIAS=discord

# Discord version
DISCORD_VERSION={discord_version}

# Patches to apply (customize via --discord-patches)
ENABLE_DEV_MODE=true
ENABLE_EXPERIMENTS=true
"""

  # Add custom patches if specified
  custom_patches = ctx.options.get("discord_patches", [])
  if custom_patches:
    settings_content += f"\nCUSTOM_PATCHES={','.join(custom_patches)}\n"

  settings_file.write_text(settings_content, encoding="utf-8")
  ctx.log(f"discord: created settings at {settings_file}")
  return settings_file


def run(ctx: Context) -> None:
  """
  Execute Discord APK patcher.

  Patches Discord Android APK using CyberL1/discord-apk-patcher.
  Enables developer mode, experiments, and custom backend support.

  Required tools:
  - apktool (APK decompilation/recompilation)
  - zipalign (APK optimization)
  - apksigner (APK signing)
  - keytool (keystore generation)

  Args:
      ctx: Pipeline context.

  Options:
      discord_keystore: Path to signing keystore (default: generated)
      discord_keystore_pass: Keystore password (default: "android")
      discord_version: Target Discord version (default: "auto")
      discord_patches: List of custom patches to apply
      discord_patcher_path: Custom patcher directory (default: clone to work_dir)
  """
  ctx.log("discord: starting Discord APK patcher")
  input_apk = ctx.current_apk or ctx.input_apk

  # Check dependencies
  deps_ok, missing_deps = check_dependencies(REQUIRED_TOOLS)
  if not deps_ok:
    ctx.log(f"discord: ERROR - Missing dependencies: {', '.join(missing_deps)}")
    ctx.log(
      "discord: Install with: pacman -S android-tools apktool jdk-openjdk"
    )
    ctx.log(
      "discord: Or: apt-get install -y android-sdk apktool openjdk-17-jdk"
    )
    return

  # Locate or clone patcher
  patcher_path = ctx.options.get("discord_patcher_path")
  if patcher_path:
    patcher_dir = Path(str(patcher_path))
  else:
    patcher_dir = ctx.work_dir / "discord-apk-patcher"
    if not clone_repository(DISCORD_PATCHER_REPO, patcher_dir, ctx):
      ctx.log("discord: failed to obtain patcher")
      return

  # Create settings.env
  _create_settings_env(patcher_dir, input_apk, ctx)

  # Execute build script
  build_script = patcher_dir / "build.sh"
  if not build_script.exists():
    ctx.log(f"discord: build.sh not found at {build_script}")
    return

  ctx.log("discord: running build.sh...")
  try:
    result = subprocess.run(
      ["bash", str(build_script)],
      cwd=patcher_dir,
      capture_output=True,
      text=True,
      timeout=900,  # 15 minute timeout
      check=False,
    )

    if result.returncode == 0:
      # Locate output APK (typically in dist/ or current dir)
      output_candidates = [
        patcher_dir / "dist" / "discord-patched.apk",
        patcher_dir / "discord-patched.apk",
        patcher_dir / "output" / "discord-patched.apk",
      ]

      output_apk = next(
        (apk for apk in output_candidates if apk.exists()), None
      )

      if output_apk:
        final_apk = ctx.output_dir / f"{input_apk.stem}.discord-patched.apk"
        shutil.copy2(output_apk, final_apk)
        ctx.set_current_apk(final_apk)
        ctx.log(f"discord: success → {final_apk}")

        # Store metadata
        ctx.metadata["discord"] = {
          "patched_apk": str(final_apk),
          "patches_applied": ctx.options.get("discord_patches", []),
        }
      else:
        ctx.log("discord: ERROR - patched APK not found in expected locations")
        if result.stdout:
          ctx.log(f"discord: stdout: {result.stdout[:500]}")
    else:
      ctx.log(f"discord: build failed (exit code: {result.returncode})")
      if result.stderr:
        ctx.log(f"discord: stderr: {result.stderr[:500]}")

  except subprocess.TimeoutExpired:
    ctx.log("discord: build timed out after 15 minutes")
  except Exception as e:
    ctx.log(f"discord: build error: {e}")
