"""Magisk module packaging engine."""

from __future__ import annotations

import shutil
import zipfile

from ..context import Context


def run(ctx: Context) -> None:
    """
    Package current APK into a Magisk Module.

    Args:
        ctx: Pipeline context.

    Raises:
        ValueError: If no input APK is available.
    """
    ctx.log("magisk: Packaging module...")

    apk = ctx.current_apk
    if not apk:
        raise ValueError("No input APK")

    module_id = ctx.options.get("magisk_id", "rvp_module")
    work_dir = ctx.work_dir / "magisk_build"

    # 1. Prepare Directory Structure
    if work_dir.exists():
        shutil.rmtree(work_dir)
    work_dir.mkdir(parents=True)

    system_dir = work_dir / "system" / "app" / str(module_id)
    system_dir.mkdir(parents=True)

    # 2. Copy APK
    dest_apk = system_dir / "base.apk"
    shutil.copy2(apk, dest_apk)

    # 3. Create module.prop
    prop_content = (
        f"id={module_id}\n"
        f"name=RVP Patched App ({apk.stem})\n"
        "version=v1.0\n"
        "versionCode=1\n"
        "author=rvp-pipeline\n"
        "description=Generated by apk-tweak pipeline\n"
    )
    (work_dir / "module.prop").write_text(prop_content, encoding="utf-8")

    # 4. Create Service Scripts (Optional stub)
    (work_dir / "service.sh").write_text("#!/system/bin/sh\n", encoding="utf-8")

    # 5. Zip it up (O(n) where n = total file count)
    zip_name = ctx.output_dir / f"{module_id}-magisk.zip"

    ctx.log(f"magisk: Zipping to {zip_name}")
    with zipfile.ZipFile(zip_name, "w", zipfile.ZIP_DEFLATED) as zf:
        for file in work_dir.rglob("*"):
            if file.is_file():
                zf.write(file, file.relative_to(work_dir))

    ctx.metadata["magisk_module"] = str(zip_name)
    ctx.log("magisk: Module created successfully")
