---
# https://megalinter.io/latest/configuration/
APPLY_FIXES: all
ENABLE: BASH,MAKEFILE,POWERSHELL,PYTHON,CSS,ENV,HTML,JSON,MARKDOWN,XML,YAML,ACTION,DOCKERFILE,EDITORCONFIG
DISABLE_LINTERS: REPOSITORY_KICS,REPOSITORY_GRYPE,SPELL_VALE,SPELL_PROSELINT,SPELL_LYCHEE,BASH_EXEC
DISABLE_ERRORS_LINTERS: SPELL_CSPELL,BASH_SHFMT,BASH_SHELLCHECK,YAML_YAMLLINT,YAML_V8R,YAML_PRETTIER,REPOSITORY_SEMGREP,REPOSITORY_GRYPE,REPOSITORY_DEVSKIM,PYTHON_BANDIT,ACTION_ACTIONLINT,MARKDOWN_MARKDOWNLINT

YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml
YAML_YAMLLINT_CLI_LINT_MODE: file
YAML_PRETTIER_CONFIG_FILE: .prettierrc.yml
YAML_PRETTIER_FILE_EXTENSIONS: [".yml", ".yaml"]
JSON_PRETTIER_CONFIG_FILE: .prettierrc.yml
JSON_PRETTIER_FILE_EXTENSIONS: [".json", ".json5", ".jsonc"]
JSON_JSONLINT_CLI_LINT_MODE: list_of_files
TOML_TAPLO_ARGUMENTS: fmt
BASH_SHELLCHECK_ARGUMENTS: "-s bash -x -a -S warning"
BASH_SHFMT_ARGUMENTS: "-ln bash -s -i 2 -bn --apply-ignore"
YAML_V8R_FILE_EXTENSIONS: [".yml", ".yaml", ".toml", ".json", ".jsonc"]
YAML_V8R_DISABLE_ERRORS: true
YAML_YAMLLINT_DISABLE_ERRORS: true
YAML_PRETTIER_DISABLE_ERRORS: true
SPELL_LYCHEE_DISABLE_ERRORS: true
BASH_EXEC_DISABLE_ERRORS: true
MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: true
ACTION_ACTIONLINT_DISABLE_ERRORS: true
IGNORE_GENERATED_FILES: true
IGNORE_GITIGNORED_FILES: true
PARALLEL: true
PYTHON_DEFAULT_STYLE: ruff
SHOW_ELAPSED_TIME: true
REPORT_OUTPUT_FOLDER: megalinter-reports
FILTER_REGEX_EXCLUDE: '(node_modules|\.git|\.github/workflows)'
FLAVOR_SUGGESTIONS: false
POST_COMMANDS:
  - command: git add -A
    continue_if_failed: false
