# Prettier Configuration
# https://prettier.io/docs/en/configuration.html

# Global settings
printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: as-needed
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always
endOfLine: lf
embeddedLanguageFormatting: auto

# File-specific overrides
overrides:
  # JavaScript/TypeScript - single quotes
  - files:
      - "*.js"
      - "*.mjs"
      - "*.cjs"
      - "*.jsx"
      - "*.ts"
      - "*.mts"
      - "*.cts"
      - "*.tsx"
    options:
      singleQuote: true
      semi: true

  # JSON - no trailing commas
  - files:
      - "*.json"
      - "*.json5"
      - "*.jsonc"
    options:
      trailingComma: none
      printWidth: 120

  # YAML
  - files:
      - "*.yml"
      - "*.yaml"
    options:
      printWidth: 120
      tabWidth: 2

  # Markdown - 80 char width
  - files:
      - "*.md"
      - "*.markdown"
    options:
      printWidth: 80
      proseWrap: always

  # CSS/SCSS
  - files:
      - "*.css"
      - "*.scss"
      - "*.sass"
      - "*.less"
    options:
      singleQuote: false
      tabWidth: 2
