# yamllint configuration
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

# Ignore patterns
ignore: |
  .git/
  node_modules/
  .venv/
  venv/
  __pycache__/
  dist/
  build/
  *.egg-info/

rules:
  # Line length
  line-length:
    max: 120
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation - enforce 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Document structure
  document-start:
    present: false
  document-end:
    present: false

  # Comments
  comments:
    min-spaces-from-content: 2
    require-starting-space: true
    ignore-shebangs: true

  comments-indentation: enable

  # Brackets & braces
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  # Colons
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # Commas
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  # Hyphens
  hyphens:
    max-spaces-after: 1

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Empty values
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: true

  # Key ordering
  key-ordering: disable

  # Duplicate keys
  key-duplicates: enable

  # New lines
  new-line-at-end-of-file: enable
  new-lines:
    type: unix

  # Truthy values
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    check-keys: false

  # Trailing spaces
  trailing-spaces: enable

  # Quoted strings
  quoted-strings:
    quote-type: any
    required: false
