---
extends: default
locale: en_US.UTF-8
# Ignore globs and files
ignore: |
  node_modules/
  .git/
  megalinter-reports/
  package-lock.json
  yarn.lock

ignore-from-file: [.gitignore, .yamlignore]
yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint"

rules:
  anchors: enable
  # Allow longer lines, warn if >120
  line-length:
    max: 120
    level: warning
  colons: enable
  commas: enable
  comments-indentation: disable
  comments:
    min-spaces-from-content: 1
    level: warning
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    level: warning
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    level: warning
  document-start: disable
  document-end: disable
  empty-lines:
    level: warning
    max: 1
    max-start: 0
    max-end: 0
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false
  hyphens: enable
  indentation:
    spaces: 2
    indent-sequences: true
    level: warning
  key-duplicates: enable
  key-ordering: disable
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  octal-values: disable
  quoted-strings:
    quote-type: any
    required: false
    level: warning
  trailing-spaces: enable
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    check-keys: false
    level: warning
  float-values: disable
