from __future__ import annotations
_A='discord_patches'
import shutil,subprocess
from pathlib import Path
from typing import cast
from..context import Context
from..utils import clone_repository
from..utils import require_input_apk
from..utils import validate_and_require_dependencies
DISCORD_PATCHER_REPO='https://github.com/CyberL1/discord-apk-patcher'
REQUIRED_TOOLS=['apktool','zipalign','apksigner','keytool']
def _create_settings_env(patcher_dir,input_apk,ctx):
	C=patcher_dir;A=ctx;B=C/'settings.env';F=A.options.get('discord_keystore',str(C/'keystore.jks'));G=A.options.get('discord_keystore_pass','android');H=A.options.get('discord_version','auto');D=f"""# Discord APK Patcher Settings
# Generated by apk-tweak pipeline

# Input APK
INPUT_APK={input_apk}

# Output directory
OUTPUT_DIR={A.output_dir}

# Keystore configuration
KEYSTORE_PATH={F}
KEYSTORE_PASS={G}
KEY_ALIAS=discord

# Discord version
DISCORD_VERSION={H}

# Patches to apply (customize via --discord-patches)
ENABLE_DEV_MODE=true
ENABLE_EXPERIMENTS=true
""";E=A.options.get(_A,[])
	if E:D+=f"\nCUSTOM_PATCHES={','.join(E)}\n"
	B.write_text(D,encoding='utf-8');A.log(f"discord: created settings at {B}");return B
def run(ctx):
	K='discord';G='discord-patched.apk';F=True;A=ctx;A.log('discord: starting Discord APK patcher');H=require_input_apk(A)
	if not validate_and_require_dependencies(A,REQUIRED_TOOLS,K,'Install with: pacman -S android-tools apktool jdk-openjdk | Or: apt-get install -y android-sdk apktool openjdk-17-jdk',fallback=F):return
	I=A.options.get('discord_patcher_path')
	if I:B=Path(cast(str,I))
	else:
		B=A.work_dir/'discord-apk-patcher'
		if not clone_repository(DISCORD_PATCHER_REPO,B,A):A.log('discord: failed to obtain patcher');return
	_create_settings_env(B,H,A);E=B/'build.sh'
	if not E.exists():A.log(f"discord: build.sh not found at {E}");return
	A.log('discord: running build.sh...')
	try:
		C=subprocess.run(['bash',str(E)],cwd=B,capture_output=F,text=F,timeout=900,check=False)
		if C.returncode==0:
			L=[B/'dist'/G,B/G,B/'output'/G];J=next((A for A in L if A.exists()),None)
			if J:D=A.output_dir/f"{H.stem}.discord-patched.apk";shutil.copy2(J,D);A.set_current_apk(D);A.log(f"discord: success → {D}");A.metadata[K]={'patched_apk':str(D),'patches_applied':A.options.get(_A,[])}
			else:
				A.log('discord: ERROR - patched APK not found in expected locations')
				if C.stdout:A.log(f"discord: stdout: {C.stdout[:500]}")
		else:
			A.log(f"discord: build failed (exit code: {C.returncode})")
			if C.stderr:A.log(f"discord: stderr: {C.stderr[:500]}")
	except subprocess.TimeoutExpired:A.log('discord: build timed out after 15 minutes')
	except(OSError,subprocess.CalledProcessError)as M:A.log(f"discord: build error: {M}")