from __future__ import annotations

APKTOOL_PATH_KEY = "apktool_path"
ZIPALIGN_PATH_KEY = "zipalign_path"
REVANCED_CLI_KEY = "revanced_cli"
REVANCED_PATCHES_KEY = "patches"
REVANCED_INTEGRATIONS_KEY = "revanced_integrations"
DEFAULT_APKTOOL = "apktool"
DEFAULT_ZIPALIGN = "zipalign"
ENGINE_REVANCED = "revanced"
ENGINE_MAGISK = "magisk"
ENGINE_LSPATCH = "lspatch"
ENGINE_DTLX = "dtlx"
ENGINE_RKPAIRIP = "rkpairip"
MMAP_FILE_SIZE_THRESHOLD = 102400
LARGE_FILE_THRESHOLD = 1048576
SMALL_FILE_THRESHOLD = 10240
MAX_WORKER_THREADS = 32
DEFAULT_CPU_MULTIPLIER = 4
